### ISSUE TITLE
is it possible to add a list of users at once?

### ISSUE THREAD

**Issue by Deybat** [albertopasqualetto/Gmail-schedule#1]
Awesome Script @albertopasqualetto 

is it possible to add a list of users at once?
also the "from name" used can it be from the gmail account rather than the username?

**Comment by albertopasqualetto** [comment]
Thanks.

What do you mean with "from name"? You mean one of [theese aliases](https://developers.google.com/apps-script/reference/gmail/gmail-app#getAliases())?

I think the list feature is a bit out of scope if added in the web interface, how would you suggest to add it? Otherwise you may add a function that bypasses the web interface to add an hardcoded list.
(If you think it only is a your momentarily necessity, I can provide you an old script that accepts an hardcoded list and, but it not interfaces with script already here on Github)

**Comment by Deybat** [comment]
Yes aliases because the email sent show-up coming with email not the name linked to the account.

as for the list of email i think using a spreadsheet would be ok (if you could share the one with hardcoded list to test it would be great)

can you confirm if this is an existing issue please
i did add 2 email in web interface but only the first one got sent and i get this error 
![Screenshot from 2022-08-15 17-59-18](https://user-images.githubusercontent.com/110777847/184681912-e0f5d643-d521-4646-83f3-48ea6eca4c28.png)

**Comment by albertopasqualetto** [comment]
[This](https://gist.github.com/albertopasqualetto/3ed9ac2eab83df51f2f932bada73832f) is the completely different code with the hardcoded list.

For the alias I will work for it as soon as possibile i will add a new field with a dropdown on the web interface and then save it within each line (if you have time, you could implement it).

Talking about the error, also I am receiving that error from the latest release, but I still did not check it since I just came back from holiday.

**Comment by Deybat** [comment]
Cool, thanks
i wish i can help but am not dev :( i really appreciate the effort.

also a great improvement would be to body rotation (so that you can change body at every execution)
and a delay between each email sent
maybe for future update

**Comment by albertopasqualetto** [comment]
I just updated it with v1.3.0; now the error above should not happen anymore and I added the alias thing. Note that nothing has been tested since I do not have so much time and I do not have aliases; please notice me if it works correctly.

Talking about the list add, it could be interesting to implement it by linking a Google spreadsheet, but, for the same reason as above, I won't implement it in a recent future.

The email delay is useless, I think (maybe it would be good selecting at what time every message should be sent, but this was not my initial intention, so I'll keep like it is.

The body rotation needs too much effort to be implemented. If someone wants it, he should add a small function for that use (or maybe use the spreadsheet, when implemented), I am here for any PR with this aim anyway.

**Comment by Deybat** [comment]
after testing it in 2 different account it seems not to work and i get "Error in sending email" in the logs 

is the code with the hardcoded list can accept html in the body?

**Comment by albertopasqualetto** [comment]
Try adding Gmail API from services on the left of the editor and retry.


Talking about html, I do not know, just try it or google it (anyway it uses the same text method as this app, so if it works there, it will also work here and vice versa).

**Comment by Deybat** [comment]
Yeah i did follow all the steps but it not working.

could please help with adding "name" parameter to code with the hardcoded list as shown [here](https://developers.google.com/apps-script/reference/gmail/gmail-app#sendemailrecipient,-subject,-body,-options)

![Screenshot from 2022-08-23 13-54-22](https://user-images.githubusercontent.com/110777847/186164267-1cfd18d2-6fc9-4450-ac4a-fc2340aa5542.png)

**Comment by albertopasqualetto** [comment]
> Yeah i did follow all the steps but it not working.

Well, so I do not know with no more hints.

>could please help with adding "name" parameter to code with the hardcoded list as shown [here](https://developers.google.com/apps-script/reference/gmail/gmail-app#sendemailrecipient,-subject,-body,-options)

Create a new function in the .gs:
``` javascript
function myAliases() {
	var aliases = GmailApp.getAliases();
	Logger.log(aliases);
}
```
Save the file, run the function myAliases from the upper bar.
In the console you get the aliases in a list. (First is  number 0, second is 1, etc.).
Then substitute line 22 with: `GmailApp.sendEmail(value.recipient, value.subject, value.body, {from: GmailApp.getAliases()[n]});` **n** is the number as said above.



Edit: did not read your answer well. What I wrote above was good for aliases. For the name you have to substitute line 22 with: `GmailApp.sendEmail(value.recipient, value.subject, value.body, {name: 'NAME_HERE'});`

**Comment by Deybat** [comment]
The edit did work for me Thanks alot.

**Comment by albertopasqualetto** [comment]
Added feature in release v1.4.0
